# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

variables:
  - name: package-version 
    value: "0.2.4-QF"

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: 'ClosedXML.Report\*.csproj'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'package-version'
    verbosityPack: 'Normal'
    configuration: 'Release'
    arguments: '-p:TargetFrameworks=netstandard2.0'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'closed_xml_package'
    publishLocation: 'Container'